[package]
name = "advent-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
num-format = "0.4"
priority-queue = "2"
fxhash = "0.2"
num-traits = "0.2"
petgraph = "0.7"
nom = "7"
bit-vec = "0.8"
smallvec = "1"
memmap2 = "0.9"