[package]
name = "advent-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8"
fxhash = "0.2"
image = "0.25.8"
memmap2 = "0.9"
nom = "8"
nom-parse-trait = "0.3.2"
num-format = "0.4"
num-traits = "0.2"
petgraph = "0.7"
priority-queue = "2"
smallvec = "1"
