[package]
name = "advent-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8"
fxhash = "0.2"
memmap2 = "0.9"
nom = "7"
nom-parse-trait = "0.2.0"
nom-parse-macros = "0.2.0"
num-format = "0.4"
num-traits = "0.2"
petgraph = "0.7"
priority-queue = "2"
smallvec = "1"
