name: Verify that all unit tests are succeeding

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        directory: [ "shared", "2022", "2023", "2024" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust to nightly
        run: rustup update nightly && rustup default nightly
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.directory }}
      - name: Run tests
        run: cargo test -- -Z unstable-options --format json --report-time | tee results.json
        working-directory: ${{ matrix.directory }}
      - name: Generate report
        uses: innoq/action-cargo-test-report@v1
        with:
          cargo-test-report-json: "${{ matrix.directory }}/results.json"
