name: Verify that all unit tests are succeeding

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: ["2021", "2022", "2023", "2024"]

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust to nightly
        run: rustup update nightly && rustup default nightly
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.projects }}
          workspaces: ${{ matrix.projects }} -> ./${{ matrix.projects }}
      - name: Run tests
        working-directory: ./${{ matrix.projects }}
        run: ../.github/cargo-test.sh

  test-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust to nightly
        run: rustup update nightly && rustup default nightly
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        working-directory: ./shared
        run: cargo test --tests --no-fail-fast
