name: Verify that all unit tests are succeeding

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust to nightly
        run: rustup update nightly && rustup default nightly
      - name: Run tests
        run: cargo test --verbose
